name: CI

on:
  push:
    branches:
      # mainブランチへのプッシュ時のみに発火
      - main 

env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app
  

jobs:
  test:
    runs-on: macOS-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin
    steps:
      - name: Show Xcode list
        run: ls /Applications | grep "Xcode"
      - name: Show Xcode version
        run: xcodebuild -version
