# ワークフロー名称
name: CI
# トリガー(条件)
on:
  push:
    branches:
      # mainブランチへのプッシュ時のみに発火
      - main 

# CI動作環境
env:
  # Xcodeの最新アプリケーションを指定
  DEVELOPER_DIR: /Applications/Xcode_26.0.1.app
  
# ジョブを定義
jobs:
  # ジョブ名を指定
  ci_build:
    # 実行環境を指定
    runs-on: macOS-latest
    # ジョブ内の各ステップを定義
    steps:
      # リポジトリのコードをチェックアウト（取得）
      - name: Checkout
        uses: actions/checkout@v4

      # Rubyのセットアップ
      - name: Set Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Cache Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # xcprettyの導入(ログ最適化)
      - name: Install Bundled Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # GoogleService-Info.plistの動的構築
      - name: Setup GoogleService-Info.plist
        run: |
          echo "$GOOGLE_SERVICE_INFO_PLIST_BASE64" | base64 --decode > $GITHUB_WORKSPACE/MinnanoTanjyoubi/GoogleService-Info.plist

      # CocoaPodsで管理しているライブラリのキャッシュ
      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      # Cocoa Podsのインストール
      - name: Install CocoaPods
        run: sudo gem install cocoapods
      # Cocoa Podsのセットアップ
      - name: Install Pods
        run: pod install --repo-update

      # 使用可能なXcodeアプリ一覧を出力する
      - name: Show Xcode list
        run: ls /Applications | grep "Xcode"
      # 実行環境のXcodeバージョンを出力する
      - name: Show Xcode version
        run: xcodebuild -version

      - name: Xcode build
        run: |
          set -o pipefail
          xcodebuild \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 17" \
            -configuration Debug \
            -workspace MinnanoTanjyoubi.xcworkspace \
            -scheme MinnanoTanjyoubi \
            build \
            ENABLE_PREVIEWS=NO \
            | bundle exec xcpretty
