name: CI

on:
  push:
    branches:
      # mainブランチへのプッシュ時のみに発火
      - main 

env:
  DEVELOPER_DIR: /Applications/Xcode_26.0.1.app
  

jobs:
  test:
    runs-on: macOS-latest
    env:
      MINT_PATH: mint/lib
      MINT_LINK_PATH: mint/bin
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: pod install --repo-update

      - name: Show Xcode list
        run: ls /Applications | grep "Xcode"
      - name: Show Xcode version
        run: xcodebuild -version

      - name: Xcode build
        run: |
          set -o pipefail
          xcodebuild \
            -sdk iphonesimulator \
            -configuration Debug \
            -workspace MinnanoTanjyoubi.xcworkspace \
            -scheme MinnanoTanjyoubi \
            build
