# ワークフロー名称
name: Run Test & Get Coverage
# トリガー(条件)
on:
  push:
    branches:
      # mainブランチへのプッシュ時のみに発火
      - feature/test-actions

# CI動作環境
env:
  # Xcodeの最新アプリケーションを指定
  DEVELOPER_DIR: /Applications/Xcode_26.0.1.app
  
# ジョブを定義
jobs:
  # ジョブ名を指定
  ci_build:
    # 実行環境を指定
    runs-on: macOS-latest
    # ジョブ内の各ステップを定義
    steps:
      # リポジトリのコードをチェックアウト（取得）
      - name: Checkout
        uses: actions/checkout@v4

      # 使用可能なXcodeアプリ一覧を出力する
      - name: Show Xcode list
        run: ls /Applications | grep "Xcode"
      # 実行環境のXcodeバージョンを出力する
      - name: Show Xcode version
        run: xcodebuild -version 

      # Rubyのセットアップ
      - name: Set Ruby version
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2

      # Gemsのキャッシュ
      - name: Cache Gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # GemFileに定義したライブラリ群のインストール
      - name: Install Bundled Gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # GoogleService-Info.plistの動的構築
      - name: Setup GoogleService-Info.plist
        run: |
          echo ${{ secrets.GOOGLE_SERVICE_INFO_PLIST_BASE64 }} | base64 --decode > $GITHUB_WORKSPACE/GoogleService-Info.plist

      # CocoaPodsで管理しているライブラリのキャッシュ
      - name: Cache Pods
        uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      # Cocoa Podsのセットアップ
      - name: Install Pods
        run: bundle exec pod install

      # SPMのライブラリのキャッシュ
      - name: Cache Swift Packages
        uses: actions/cache@v4
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-

      # Xcodeビルド
      - name: Run Xcode Test
        run: |
          set -o pipefail
          xcodebuild \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 17" \
            -configuration Debug \
            -workspace MinnanoTanjyoubi.xcworkspace \
            -scheme MinnanoTanjyoubi \
            -enableCodeCoverage YES \
            test \
            ENABLE_PREVIEWS=NO \
            | bundle exec xcpretty

      # カバレッジレポートの作成
      - name: Generate Coverage Report
        run: |
          slather coverage \
            --html \
            --output-directory slather-report \
            --scheme MinnanoTanjyoubi \
            --workspace MinnanoTanjyoubi.xcworkspace \

      # カバレッジレポートのアーティファクト化
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: slather-report
